"""
Django settings for basic project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

env = environ.Env()
environ.Env.read_env()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "home.apps.HomeConfig",
    "services.apps.ServicesConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "basic.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "basic.wsgi.app"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),  # Or your IP address
        'PORT': env("DB_PORT"),  # Default is 5432
        'OPTIONS': {
                'sslmode': 'verify-full',
                'sslrootcert': '-----BEGIN CERTIFICATE-----
MIIEUDCCArigAwIBAgIUMkaSw/+lJOs3ZMezAIeKi+9+JOEwDQYJKoZIhvcNAQEM
BQAwQDE+MDwGA1UEAww1MmIyODEwYzAtZTYyMy00OWYzLWE3M2YtMDhiY2Y4ZTY1
ODM1IEdFTiAxIFByb2plY3QgQ0EwHhcNMjUwNzAzMTcyMzQzWhcNMzUwNzAxMTcy
MzQzWjBAMT4wPAYDVQQDDDUyYjI4MTBjMC1lNjIzLTQ5ZjMtYTczZi0wOGJjZjhl
NjU4MzUgR0VOIDEgUHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCC
AYoCggGBALswCheGJrKftWWpo7ZawK7MrVqgfpBHH7whqIrFu8boxEWplGv/9NIN
Ax8vlDoRN3qyOUujTVDB7omQCmoLerCGLq6uA58l9lf9bLwLMgWMnhIyuvxibVZI
L6vmyGZcuc2CTl3JoWuTk5LiRyEuZSPoiVw7/LWVdATn+9u8PR3MNhF2uDPhBJrr
avSm5hICFchq4H9KhCpyNd1jjGMNaAsl1Hx8fULroNhQvjQwM+mu8uDH9ux1jL80
HvMoOoOWtReOnl2wNrPWRaUwx6Qyhh+6boZVLtz8lmgwahzsMuHMx0qgWVpSEGeS
xPociK2MO+chs9jLF8mtaK/B1oY2CNKEdjh/Re+XSmF7G4SHekKaeMaZdABJvPsl
8qx2B0jX4/bf7siVYQCD9L2z9+UEqnZ7yXeUtNNN68RfZAevjv/+0UQwyZCOZ5cy
nzXBcE5B/PKf/TSWRhtivHQUbW7x4gnLD3fXwgs+m7Yx2E/3s2fV8CQQcNWnTfxz
XpOXmrergQIDAQABo0IwQDAdBgNVHQ4EFgQUGbvY0fTehlxx4nxrujItAGNdiPAw
EgYDVR0TAQH/BAgwBgEB/wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQAD
ggGBAIgut039QlLoWu33wUBzlqjolWiEoEYZcLuo/0nBbF6W9hM73Htg/rL28+w0
bZ+vpiC8nzE+aqW2imVZrT9Wmh2fS6giDFJBI8L1KDWmI/xkcvlrw9obQrvW21wO
uxo5zbKPHpHD6y6zimH9bKIAT8Hp8SmiE1qIo5PBNw+GX4iLaopqT8/b+QzQIN41
IB//TWgKEUrmHaVfDh3HMDvzI0IV+wb6XjTp7B0arVqcXNZmQQheDIrSFqV8WGTR
jQ8EnH5vzjQuQasX4gd2DDsMuzrXFmGeNinq0tzqy3fUysJKFmYan17diY+EuT96
GTfmkoTVpvt53h57w6n7/JOZ7cEg/aVIoszQbrZOCBLTLezXSxVd4DH+EUKotDF9
DCO2bYkUzAtW+qj9f978sINR4vgPD2G+Azza4B5xsDt9drsKI925avBQ4iH0EE9a
TXQ4gqkiDCz591PFUwvdYrRxqQqDaYrhQ0xAxdvrHVRI0ijJIPUaXe5+asr8Dem2
GtzA0g==
-----END CERTIFICATE-----
',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# Add manually

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
